# Generated by Django 4.2.4 on 2023-10-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpage',
            name='address',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
